pip install pystyle 
pip install pyfiglet 
pip install datetime
pip install sys-toolkit
pip install clear
pip install colorama
pip install os-sys
pip install sockets
pip install thread 
pip install pyfiglet 
pip install phonenumbers 
pip install PyQt5
pip install tls_client
pip install ZipFile
pip install Path
pip install tqdm
pip install bs4
pip install fade~=0.0.9
pip install lxml~=4.9.2
pip install colorama~=0.4.5
pip install fake-useragent~=1.2.1
pip install aiohttp~=3.8.4
pip install urllib3~=1.26.10
pip install requests~=2.31.0
pip install beautifulsoup4~=4.11.1
pip install pythonping~=1.1.4
pip install httpagentparser~=1.9.5
pip install cloudscraper~=1.2.69
pip install opentele~=1.15.1
pip install ua-parser~=0.16.1
pip install discord
pip install python-http-client
pip install charset_normalizer
pip install 2captcha-python
pip install beautifulsoup4
pip install pyinstaller
pip install pylibcheck
pip install pyperclip
pip install pyautogui
pip install pypiwin32
pip install websocket
pip install packaging
pip install requests
pip install datetime
pip install requests
pip install selenium
pip install keyboard
pip install colorama
pip install urlopen
pip install colored
pip install discord
pip install asyncio
pip install PyNaCl
pip install easygui
pip install tasksio
pip install pystyle
pip install discum
pip install Cipher
pip install colour
pip install Popen
pip install login
pip install pillow
pip install psutil
pip install emoji
pip install httpx
pip install loads
pip install tqdm
pip install pipe
pip install fore
pip install aes


color b
python tool.py
